### ISSUE TITLE
Error creating label: Bad Request Empty name

### ISSUE THREAD

**Issue by msbentsen** [wbthomason/zotodo#5] opened 2020-07-15 09:17 UTC
First of all thanks for an awesome add-on! I just installed 0.5.0, set my API token and hit "Create Todoist task" for an item in my library, but got the error: 
![premium](https://user-images.githubusercontent.com/47495444/87527225-1a77c780-c68c-11ea-9ea7-f52a08d67103.png)

Apparently, "Labels" is a premium feature at Todoist. For my application I don't really need to set a label, but removing the label from the Zotodo preference gives me the error:
![empty](https://user-images.githubusercontent.com/47495444/87527403-5f036300-c68c-11ea-9e94-36aa5bd4944d.png)

Do I need to get premium at Todoist to use Zotodo? Or how can I get around this error? Thanks!

**Comment by wbthomason** [comment] 2020-07-15 14:16
Nope, that looks like a regression bug; I can reproduce it on my end. I'll take a look and fix it. Thanks for the report!

**Comment by wbthomason** [comment] 2020-07-15 14:46
Should be fixed in v0.5.1 (just pushed); please let me know if you still have trouble!

**Closed as completed** 2020-07-15 14:46 UTC
Labels: bug

**Comment by msbentsen** [comment] 2020-07-15 15:10
Works great, thank you for the quick fix :-)
